yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(),
        name='password_change'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/comment_form.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-comment">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a class='btn-author' href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text|linebreaksbr }}
      </p>
    </div>
  </div>
{% endfor %} 

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color: #fff">Yatube</span>
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link link-light"
             href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light"
            href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link link-light"
          href="{% url 'posts:post_create'%}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light"
            href="{% url 'users:password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light"
            href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li class="link-light">
          Пользователь: <a class="btn-author link-light" href="{% url 'posts:profile' user.username %}">{{ user.username }}</a>
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light" 
          href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" 
          href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>      
</header> 

yatube/templates/includes/ul.html
<ul>
  <li>
    <span class="span">Автор:</span>
    <a class="btn-author" href="{% url 'posts:profile' post.author.username %}">
      <span class="span-name">{{ post.author.get_full_name }}</span>
    </a>
  </li>
  <li>
    <span class="span">Дата публикации:</span> <span class="span-name">{{ post.pub_date|date:"d E Y" }}</span>
  </li>
</ul>